<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ObatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $obatData = [
            [
                'kode_obat' => 'O2500376',
                'barcode' => 'O2500376250001',
                'nama_obat' => 'ALBENDAZOLE 400 MG (IPF)',
                'satuan' => 'Tablet',
                'stok' => 222,
                'harga_beli' => 467,
                'harga_jual' => 500,
                'kadaluwarsa' => '2028-09-26',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500511',
                'barcode' => 'O2500511250001',
                'nama_obat' => 'Allopurinol 100 mg (IPF)',
                'satuan' => 'Tablet',
                'stok' => 0,
                'harga_beli' => 155,
                'harga_jual' => 200,
                'kadaluwarsa' => '2027-07-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500190',
                'barcode' => 'O2500190250001',
                'nama_obat' => 'AMOXICILLIN 500 MG (IPF)',
                'satuan' => 'Tablet',
                'stok' => 785,
                'harga_beli' => 544,
                'harga_jual' => 600,
                'kadaluwarsa' => '2029-06-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500191',
                'barcode' => 'O2500191250001',
                'nama_obat' => 'IPF.AMOXICILLIN SIRUP 125 MG/5 ML',
                'satuan' => 'Botol',
                'stok' => 24,
                'harga_beli' => 4000,
                'harga_jual' => 4000,
                'kadaluwarsa' => '2027-02-28',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500910',
                'barcode' => 'O2500910250001',
                'nama_obat' => 'BETAMETHASONE KRIM 5 GR (IPF)',
                'satuan' => 'Tube',
                'stok' => 25,
                'harga_beli' => 1998,
                'harga_jual' => 2000,
                'kadaluwarsa' => '2027-08-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500653',
                'barcode' => 'O2500653250001',
                'nama_obat' => 'IPF. Diazepam 5 mg RT/ Stesolid RT 5 mg/ 25 ml',
                'satuan' => 'Tube',
                'stok' => 5,
                'harga_beli' => 13665,
                'harga_jual' => 14000,
                'kadaluwarsa' => '2027-09-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500673',
                'barcode' => 'O2500673250001',
                'nama_obat' => 'IPF. Fenobarbital inj 50 mg/ml- 2 ml',
                'satuan' => 'Ampul',
                'stok' => 33,
                'harga_beli' => 1700,
                'harga_jual' => 2000,
                'kadaluwarsa' => '2026-01-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500271',
                'barcode' => 'O2500271250001',
                'nama_obat' => 'IPF.GARAM ORALIT',
                'satuan' => 'Sachet',
                'stok' => 59,
                'harga_beli' => 475,
                'harga_jual' => 500,
                'kadaluwarsa' => '2026-02-28',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500573',
                'barcode' => 'O2500573250001',
                'nama_obat' => 'Hydrochlorothiazide/HCT 25 mg (IPF)',
                'satuan' => 'Tablet',
                'stok' => 92,
                'harga_beli' => 202,
                'harga_jual' => 250,
                'kadaluwarsa' => '2027-03-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500897',
                'barcode' => 'O2500897250001',
                'nama_obat' => 'IPF. TTD / Tablet Tambah Darah',
                'satuan' => 'Kaplet',
                'stok' => 1603,
                'harga_beli' => 195,
                'harga_jual' => 200,
                'kadaluwarsa' => '2026-03-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500382',
                'barcode' => 'O2500382250001',
                'nama_obat' => 'IPF.IBUPROFEN 200 MG',
                'satuan' => 'Tablet',
                'stok' => 144,
                'harga_beli' => 146,
                'harga_jual' => 200,
                'kadaluwarsa' => '2026-05-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500431',
                'barcode' => 'O2500431250001',
                'nama_obat' => 'IPF.1025.Kotrimoksazole 480 mg',
                'satuan' => 'Tablet',
                'stok' => 94,
                'harga_beli' => 243,
                'harga_jual' => 250,
                'kadaluwarsa' => '2028-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500577',
                'barcode' => 'O2500577250001',
                'nama_obat' => 'Methylergometrine 0.125 mg (IPF)',
                'satuan' => 'Tablet',
                'stok' => 94,
                'harga_beli' => 216,
                'harga_jual' => 250,
                'kadaluwarsa' => '2027-04-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500947',
                'barcode' => 'O2500947250001',
                'nama_obat' => 'Methylergometrine 0.2 mg/ml Injeksi (IPF)',
                'satuan' => 'Ampul',
                'stok' => 10,
                'harga_beli' => 2000,
                'harga_jual' => 2000,
                'kadaluwarsa' => '2027-04-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500691',
                'barcode' => 'O2500691250001',
                'nama_obat' => 'IPF. Lidocain Comp. 2 % injeksi 2 ml',
                'satuan' => 'Ampul',
                'stok' => 4,
                'harga_beli' => 1848,
                'harga_jual' => 2000,
                'kadaluwarsa' => '2026-09-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500301',
                'barcode' => 'O2500301250001',
                'nama_obat' => 'IPF.MGSO4 20%',
                'satuan' => 'fls',
                'stok' => 4,
                'harga_beli' => 5470,
                'harga_jual' => 5500,
                'kadaluwarsa' => '2027-11-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500302',
                'barcode' => 'O2500302250001',
                'nama_obat' => 'IPF. MGSO4 40%',
                'satuan' => 'fls',
                'stok' => 3,
                'harga_beli' => 6227,
                'harga_jual' => 6500,
                'kadaluwarsa' => '2027-11-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500697',
                'barcode' => 'O2500697250001',
                'nama_obat' => 'IPF. Nystatin 100.000 IU',
                'satuan' => 'Buah',
                'stok' => 10,
                'harga_beli' => 1832,
                'harga_jual' => 2000,
                'kadaluwarsa' => '2026-09-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500416',
                'barcode' => 'O2500416250001',
                'nama_obat' => 'IPF.1025.FDC Dewasa Kat 1',
                'satuan' => 'Paket',
                'stok' => 916,
                'harga_beli' => 500,
                'harga_jual' => 500,
                'kadaluwarsa' => '2027-07-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500417',
                'barcode' => 'O2500417250001',
                'nama_obat' => 'IPF.1025.FDC Anak',
                'satuan' => 'Paket',
                'stok' => 1000,
                'harga_beli' => 500,
                'harga_jual' => 500,
                'kadaluwarsa' => '2027-07-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501841',
                'barcode' => 'O2501841250001',
                'nama_obat' => 'IPF. Oxytocin 10 IU/ml Injeksi',
                'satuan' => 'Ampul',
                'stok' => 62,
                'harga_beli' => 3200,
                'harga_jual' => 3500,
                'kadaluwarsa' => '2026-08-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500876',
                'barcode' => 'O2500876250001',
                'nama_obat' => 'IPF. Povidon Iodin 300 ml',
                'satuan' => 'Botol',
                'stok' => 3,
                'harga_beli' => 25000,
                'harga_jual' => 25000,
                'kadaluwarsa' => '2029-08-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500250',
                'barcode' => 'O2500250250001',
                'nama_obat' => 'IPF.RANITIDIN 150 mg HJ',
                'satuan' => 'Tablet',
                'stok' => 98,
                'harga_beli' => 149,
                'harga_jual' => 150,
                'kadaluwarsa' => '2026-06-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500264',
                'barcode' => 'O2500264250001',
                'nama_obat' => 'IPF. SALBUTAMOL TABLET 2 mg',
                'satuan' => 'Tablet',
                'stok' => 124,
                'harga_beli' => 77,
                'harga_jual' => 100,
                'kadaluwarsa' => '2026-08-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500592',
                'barcode' => 'O2500592250001',
                'nama_obat' => 'Salep 2-4 (IPF)',
                'satuan' => 'Pot',
                'stok' => 72,
                'harga_beli' => 2333,
                'harga_jual' => 2500,
                'kadaluwarsa' => '2027-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501526',
                'barcode' => 'O2501526250001',
                'nama_obat' => 'ZINK 20MG - IPF',
                'satuan' => 'Tablet',
                'stok' => 127,
                'harga_beli' => 138,
                'harga_jual' => 150,
                'kadaluwarsa' => '2026-01-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500238',
                'barcode' => 'O2500238250001',
                'nama_obat' => 'IPF.ACYCLOVIR SALEP KULIT',
                'satuan' => 'Tube',
                'stok' => 26,
                'harga_beli' => 3950,
                'harga_jual' => 4000,
                'kadaluwarsa' => '2027-10-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500261',
                'barcode' => 'O2500261250001',
                'nama_obat' => 'IPF. FITOMENADION/ VIT K INJEKSI',
                'satuan' => 'Ampul',
                'stok' => 240,
                'harga_beli' => 3437,
                'harga_jual' => 3500,
                'kadaluwarsa' => '2027-03-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500016',
                'barcode' => 'O2500016250001',
                'nama_obat' => 'IBUPROFEN 400mg',
                'satuan' => 'Tablet',
                'stok' => 100,
                'harga_beli' => 60,
                'harga_jual' => 100,
                'kadaluwarsa' => '2026-09-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500298',
                'barcode' => 'O2500298250001',
                'nama_obat' => 'IPF.ISOSORBIDE DINITRATE (ISDN)',
                'satuan' => 'Tablet',
                'stok' => 63,
                'harga_beli' => 400,
                'harga_jual' => 400,
                'kadaluwarsa' => '2028-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500381',
                'barcode' => 'O2500381250001',
                'nama_obat' => 'IPF.VIT A 200.000 IU',
                'satuan' => 'Kapsul',
                'stok' => 100,
                'harga_beli' => 683,
                'harga_jual' => 700,
                'kadaluwarsa' => '2026-01-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2502741',
                'barcode' => 'O2502741250001',
                'nama_obat' => 'MMS (Multivitamin Ibu Hamil) - IPF',
                'satuan' => 'Botol',
                'stok' => 56,
                'harga_beli' => 5000,
                'harga_jual' => 5000,
                'kadaluwarsa' => '2027-11-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500888',
                'barcode' => 'O2500888250001',
                'nama_obat' => 'Diazepam 5 mg (IPF)',
                'satuan' => 'Tablet',
                'stok' => 90,
                'harga_beli' => 108,
                'harga_jual' => 150,
                'kadaluwarsa' => '2028-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500193',
                'barcode' => 'O2500193250001',
                'nama_obat' => 'IPF.BACITRACIN SALEP KULIT',
                'satuan' => 'Tube',
                'stok' => 0,
                'harga_beli' => 4400,
                'harga_jual' => 4500,
                'kadaluwarsa' => '2026-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2502064',
                'barcode' => 'O2502064250001',
                'nama_obat' => 'TLE / Tenofovir 300 mg + Lamivudin 300 mg + Efavirens 600 mg (IPF)',
                'satuan' => 'Tablet',
                'stok' => 60,
                'harga_beli' => 6900,
                'harga_jual' => 7000,
                'kadaluwarsa' => '2028-04-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500982',
                'barcode' => 'O2500982250001',
                'nama_obat' => 'Ringer Lactate 500 ml (IPF)',
                'satuan' => 'Flabot',
                'stok' => 28,
                'harga_beli' => 8000,
                'harga_jual' => 8000,
                'kadaluwarsa' => '2027-06-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500240',
                'barcode' => 'O2500240250001',
                'nama_obat' => 'JKN.ACYCLOVIR TABLET 400 mg',
                'satuan' => 'Tablet',
                'stok' => 121,
                'harga_beli' => 830,
                'harga_jual' => 850,
                'kadaluwarsa' => '2028-11-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500457',
                'barcode' => 'O2500457250001',
                'nama_obat' => 'Asam Mefenamat 500mg - BLUD',
                'satuan' => 'Tablet',
                'stok' => 468,
                'harga_beli' => 266,
                'harga_jual' => 300,
                'kadaluwarsa' => '2027-02-28',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501086',
                'barcode' => 'O2501086250001',
                'nama_obat' => 'ATTAPULGITE 600 MG (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 134,
                'harga_beli' => 302,
                'harga_jual' => 350,
                'kadaluwarsa' => '2028-02-29',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501693',
                'barcode' => 'O2501693250001',
                'nama_obat' => 'Bromhexine HCl 8 mg (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 176,
                'harga_beli' => 203,
                'harga_jual' => 250,
                'kadaluwarsa' => '2027-08-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501590',
                'barcode' => 'O2501590250001',
                'nama_obat' => 'Aminofilin 200 mg (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 79,
                'harga_beli' => 285,
                'harga_jual' => 300,
                'kadaluwarsa' => '2026-01-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500039',
                'barcode' => 'O2500039250001',
                'nama_obat' => 'AMLODIPIN 5mg (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 1260,
                'harga_beli' => 95,
                'harga_jual' => 100,
                'kadaluwarsa' => '2027-07-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500040',
                'barcode' => 'O2500040250001',
                'nama_obat' => 'AMLODIPIN 10mg (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 1511,
                'harga_beli' => 130,
                'harga_jual' => 150,
                'kadaluwarsa' => '2027-06-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501022',
                'barcode' => 'O2501022250001',
                'nama_obat' => 'Allopurinol 100 mg (BLUD 6.25)',
                'satuan' => 'Tablet',
                'stok' => 457,
                'harga_beli' => 189,
                'harga_jual' => 200,
                'kadaluwarsa' => '2027-03-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500019',
                'barcode' => 'O2500019250001',
                'nama_obat' => 'Ambroxol 30 mg - BLUD',
                'satuan' => 'Tablet',
                'stok' => 368,
                'harga_beli' => 133,
                'harga_jual' => 150,
                'kadaluwarsa' => '2028-06-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500049',
                'barcode' => 'O2500049250001',
                'nama_obat' => 'JKN. ANTASIDA TABLET',
                'satuan' => 'Tablet',
                'stok' => 289,
                'harga_beli' => 126,
                'harga_jual' => 130,
                'kadaluwarsa' => '2027-04-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500456',
                'barcode' => 'O2500456250001',
                'nama_obat' => 'Asam Folat 1mg - BLUD',
                'satuan' => 'Tablet',
                'stok' => 85,
                'harga_beli' => 138,
                'harga_jual' => 150,
                'kadaluwarsa' => '2026-10-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501476',
                'barcode' => 'O2501476250001',
                'nama_obat' => 'METAMIZOLE 500MG - BLUD',
                'satuan' => 'Tablet',
                'stok' => 146,
                'harga_beli' => 287,
                'harga_jual' => 300,
                'kadaluwarsa' => '2028-05-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500459',
                'barcode' => 'O2500459250001',
                'nama_obat' => 'Asam Tranexamat 500mg - BLUD',
                'satuan' => 'Tablet',
                'stok' => 6,
                'harga_beli' => 1568,
                'harga_jual' => 2000,
                'kadaluwarsa' => '2028-06-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500460',
                'barcode' => 'O2500460250001',
                'nama_obat' => 'Asam Asetilsalisilat 100mg (Aspilets Chewable) - BLUD',
                'satuan' => 'Tablet',
                'stok' => 105,
                'harga_beli' => 900,
                'harga_jual' => 900,
                'kadaluwarsa' => '2027-05-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501087',
                'barcode' => 'O2501087250001',
                'nama_obat' => 'BETAHISTINE 6 MG (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 87,
                'harga_beli' => 238,
                'harga_jual' => 250,
                'kadaluwarsa' => '2026-11-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501690',
                'barcode' => 'O2501690250001',
                'nama_obat' => 'Bisakodil 5 mg (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 82,
                'harga_beli' => 500,
                'harga_jual' => 500,
                'kadaluwarsa' => '2027-02-28',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501885',
                'barcode' => 'O2501885250001',
                'nama_obat' => 'BISOPROLOL 5 MG (JKN)',
                'satuan' => 'Tablet',
                'stok' => 220,
                'harga_beli' => 317,
                'harga_jual' => 350,
                'kadaluwarsa' => '2026-09-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501694',
                'barcode' => 'O2501694250001',
                'nama_obat' => 'Triamcinolone Acetonide (Bufacomb iob) (BLUD)',
                'satuan' => 'Tube',
                'stok' => 23,
                'harga_beli' => 9434,
                'harga_jual' => 9500,
                'kadaluwarsa' => '2028-06-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500464',
                'barcode' => 'O2500464250001',
                'nama_obat' => 'Captopril 25mg - BLUD',
                'satuan' => 'Tablet',
                'stok' => 278,
                'harga_beli' => 111,
                'harga_jual' => 150,
                'kadaluwarsa' => '2028-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501741',
                'barcode' => 'O2501741250001',
                'nama_obat' => 'BLUD.CEFIXIME 200 MG',
                'satuan' => 'Kapsul',
                'stok' => 1000,
                'harga_beli' => 1330,
                'harga_jual' => 1400,
                'kadaluwarsa' => '2027-01-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501739',
                'barcode' => 'O2501739250001',
                'nama_obat' => 'BLUD.CEFIXIME 100 MG',
                'satuan' => 'Kapsul',
                'stok' => 54,
                'harga_beli' => 857,
                'harga_jual' => 900,
                'kadaluwarsa' => '2026-11-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501104',
                'barcode' => 'O2501104250001',
                'nama_obat' => 'BLUD. CETIRIZIN 10 MG',
                'satuan' => 'Tablet',
                'stok' => 95,
                'harga_beli' => 96,
                'harga_jual' => 100,
                'kadaluwarsa' => '2026-10-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500150',
                'barcode' => 'O2500150250001',
                'nama_obat' => 'BLUD. CEFADROXIL 500 mg',
                'satuan' => 'Kapsul',
                'stok' => 139,
                'harga_beli' => 1092,
                'harga_jual' => 1100,
                'kadaluwarsa' => '2027-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2503067',
                'barcode' => 'O2503067250001',
                'nama_obat' => 'COPARCETIN - BLUD',
                'satuan' => 'Tablet',
                'stok' => 308,
                'harga_beli' => 621,
                'harga_jual' => 650,
                'kadaluwarsa' => '2026-10-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500871',
                'barcode' => 'O2500871250001',
                'nama_obat' => 'BLUD. Kotrimoksazole Suspensi',
                'satuan' => 'Botol',
                'stok' => 66,
                'harga_beli' => 5200,
                'harga_jual' => 5200,
                'kadaluwarsa' => '2026-10-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501195',
                'barcode' => 'O2501195250001',
                'nama_obat' => 'CTM 4 MG (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 2335,
                'harga_beli' => 77,
                'harga_jual' => 80,
                'kadaluwarsa' => '2025-11-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2503094',
                'barcode' => 'O2503094250001',
                'nama_obat' => 'JKN.CURCUMA FORCE',
                'satuan' => 'Kapsul',
                'stok' => 96,
                'harga_beli' => 1430,
                'harga_jual' => 1500,
                'kadaluwarsa' => '2026-09-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500901',
                'barcode' => 'O2500901250001',
                'nama_obat' => 'BLUD. Daneuron',
                'satuan' => 'Tablet',
                'stok' => 127,
                'harga_beli' => 518,
                'harga_jual' => 550,
                'kadaluwarsa' => '2027-02-28',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501196',
                'barcode' => 'O2501196250001',
                'nama_obat' => 'DEXAMETASON 05 MG (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 233,
                'harga_beli' => 69,
                'harga_jual' => 70,
                'kadaluwarsa' => '2028-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501407',
                'barcode' => 'O2501407250001',
                'nama_obat' => 'BLUD.DIFENHIDRAMIN INJEKSI',
                'satuan' => 'Vial',
                'stok' => 36,
                'harga_beli' => 10500,
                'harga_jual' => 10500,
                'kadaluwarsa' => '2026-01-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500151',
                'barcode' => 'O2500151250001',
                'nama_obat' => 'BLUD.Domperidone Maleat 10 mg',
                'satuan' => 'Tablet',
                'stok' => 237,
                'harga_beli' => 172,
                'harga_jual' => 200,
                'kadaluwarsa' => '2027-11-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501198',
                'barcode' => 'O2501198250001',
                'nama_obat' => 'DIMENHYDRINATE 50 MG (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 108,
                'harga_beli' => 208,
                'harga_jual' => 250,
                'kadaluwarsa' => '2026-06-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501469',
                'barcode' => 'O2501469250001',
                'nama_obat' => 'GENTAMICIN SALEP KULIT - BLUD',
                'satuan' => 'Tube',
                'stok' => 20,
                'harga_beli' => 4900,
                'harga_jual' => 5000,
                'kadaluwarsa' => '2027-05-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501251',
                'barcode' => 'O2501251250001',
                'nama_obat' => 'GUAIFENESIN 100 MG / GG (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 290,
                'harga_beli' => 157,
                'harga_jual' => 200,
                'kadaluwarsa' => '2028-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500479',
                'barcode' => 'O2500479250001',
                'nama_obat' => 'BLUD. GLIBENCLAMIDE',
                'satuan' => 'Tablet',
                'stok' => 7,
                'harga_beli' => 321,
                'harga_jual' => 350,
                'kadaluwarsa' => '2027-04-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500473',
                'barcode' => 'O2500473250001',
                'nama_obat' => 'Glimepiride 2mg - BLUD',
                'satuan' => 'Tablet',
                'stok' => 111,
                'harga_beli' => 260,
                'harga_jual' => 300,
                'kadaluwarsa' => '2028-05-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2502214',
                'barcode' => 'O2502214250001',
                'nama_obat' => 'BLUD.1025.ICHTYOL SALEP KULIT',
                'satuan' => 'Pot',
                'stok' => 17,
                'harga_beli' => 7200,
                'harga_jual' => 7200,
                'kadaluwarsa' => '2027-10-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500347',
                'barcode' => 'O2500347250001',
                'nama_obat' => 'JKN. DEXAMETHASON INJEKSI',
                'satuan' => 'Ampul',
                'stok' => 7,
                'harga_beli' => 2170,
                'harga_jual' => 2500,
                'kadaluwarsa' => '2027-01-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500227',
                'barcode' => 'O2500227250001',
                'nama_obat' => 'JKN. HIDROKORTISON SALEP',
                'satuan' => 'Tube',
                'stok' => 17,
                'harga_beli' => 2325,
                'harga_jual' => 2500,
                'kadaluwarsa' => '2027-08-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501097',
                'barcode' => 'O2501097250001',
                'nama_obat' => 'KALSIUM LAKTAT 500 MG (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 724,
                'harga_beli' => 164,
                'harga_jual' => 200,
                'kadaluwarsa' => '2029-04-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501014',
                'barcode' => 'O2501014250001',
                'nama_obat' => 'Kaotin Suspensi 60 ml (BLUD 10.24)',
                'satuan' => 'Botol',
                'stok' => 17,
                'harga_beli' => 10700,
                'harga_jual' => 10700,
                'kadaluwarsa' => '2027-03-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501255',
                'barcode' => 'O2501255250001',
                'nama_obat' => 'BLUD. KETOKONAZOLE 200 MG',
                'satuan' => 'Tablet',
                'stok' => 63,
                'harga_beli' => 510,
                'harga_jual' => 550,
                'kadaluwarsa' => '2027-03-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501553',
                'barcode' => 'O2501553250001',
                'nama_obat' => 'BLUD. KHLORAMFENIKOL SALEP MATA',
                'satuan' => 'Tube',
                'stok' => 10,
                'harga_beli' => 11800,
                'harga_jual' => 12000,
                'kadaluwarsa' => '2028-05-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501924',
                'barcode' => 'O2501924250001',
                'nama_obat' => 'Fenol Gliserol (BLUD)',
                'satuan' => 'Botol',
                'stok' => 12,
                'harga_beli' => 10111,
                'harga_jual' => 10500,
                'kadaluwarsa' => '2027-01-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501321',
                'barcode' => 'O2501321250001',
                'nama_obat' => 'BLUD. KHLORAMFENIKOL TETES MATA',
                'satuan' => 'Botol',
                'stok' => 32,
                'harga_beli' => 11000,
                'harga_jual' => 11000,
                'kadaluwarsa' => '2026-11-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500222',
                'barcode' => 'O2500222250001',
                'nama_obat' => 'JKN.KLORAM TETES TELINGA',
                'satuan' => 'fls',
                'stok' => 57,
                'harga_beli' => 10300,
                'harga_jual' => 10500,
                'kadaluwarsa' => '2027-01-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500290',
                'barcode' => 'O2500290250001',
                'nama_obat' => 'BLUD.KHLORAMFENIKOL 250 mg HOLI',
                'satuan' => 'Kapsul',
                'stok' => 200,
                'harga_beli' => 1200,
                'harga_jual' => 1200,
                'kadaluwarsa' => '2028-07-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2502792',
                'barcode' => 'O2502792250001',
                'nama_obat' => 'LORATADINE (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 222,
                'harga_beli' => 354,
                'harga_jual' => 400,
                'kadaluwarsa' => '2028-04-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2502877',
                'barcode' => 'O2502877250001',
                'nama_obat' => 'BLUD.Lodecon Forte Tab',
                'satuan' => 'Tablet',
                'stok' => 357,
                'harga_beli' => 520,
                'harga_jual' => 550,
                'kadaluwarsa' => '2026-06-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2502399',
                'barcode' => 'O2502399250001',
                'nama_obat' => 'LOPERAMID 2 MG - BLUD',
                'satuan' => 'Tablet',
                'stok' => 135,
                'harga_beli' => 125,
                'harga_jual' => 150,
                'kadaluwarsa' => '2028-07-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501973',
                'barcode' => 'O2501973250001',
                'nama_obat' => 'Metoklopramid 10 mg (Norvom) (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 146,
                'harga_beli' => 195,
                'harga_jual' => 200,
                'kadaluwarsa' => '2026-08-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501831',
                'barcode' => 'O2501831250001',
                'nama_obat' => 'BLUD. Miconazole cream 2%',
                'satuan' => 'Tube',
                'stok' => 5,
                'harga_beli' => 4600,
                'harga_jual' => 4600,
                'kadaluwarsa' => '2028-02-29',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500477',
                'barcode' => 'O2500477250001',
                'nama_obat' => 'Metformin 500mg - BLUD',
                'satuan' => 'Tablet',
                'stok' => 341,
                'harga_beli' => 249,
                'harga_jual' => 250,
                'kadaluwarsa' => '2027-03-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501224',
                'barcode' => 'O2501224250001',
                'nama_obat' => 'BLUD. Methylprednisolon 4 mg',
                'satuan' => 'Tablet',
                'stok' => 300,
                'harga_beli' => 202,
                'harga_jual' => 250,
                'kadaluwarsa' => '2027-03-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501440',
                'barcode' => 'O2501440250001',
                'nama_obat' => 'BLUD.1025.NATRIUM DIKLOFENAK 50 MG',
                'satuan' => 'Tablet',
                'stok' => 304,
                'harga_beli' => 168,
                'harga_jual' => 200,
                'kadaluwarsa' => '2030-04-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501327',
                'barcode' => 'O2501327250001',
                'nama_obat' => 'NEOCENTA GEL (BLUD)',
                'satuan' => 'Tube',
                'stok' => 7,
                'harga_beli' => 16600,
                'harga_jual' => 16000,
                'kadaluwarsa' => '2027-01-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501122',
                'barcode' => 'O2501122250001',
                'nama_obat' => 'BLUD. NEPHROLIT',
                'satuan' => 'Kaplet',
                'stok' => 59,
                'harga_beli' => 536,
                'harga_jual' => 550,
                'kadaluwarsa' => '2026-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500482',
                'barcode' => 'O2500482250001',
                'nama_obat' => 'BLUD. NIFEDIPIN 10 MG',
                'satuan' => 'Tablet',
                'stok' => 121,
                'harga_beli' => 192,
                'harga_jual' => 200,
                'kadaluwarsa' => '2027-03-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500156',
                'barcode' => 'O2500156250001',
                'nama_obat' => 'BLUD.PEHACAIN INJ (LIDOCAIN COMP)',
                'satuan' => 'Ampul',
                'stok' => 40,
                'harga_beli' => 4000,
                'harga_jual' => 4000,
                'kadaluwarsa' => '2026-08-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501232',
                'barcode' => 'O2501232250001',
                'nama_obat' => 'BLUD. Omeprazole 20 mg',
                'satuan' => 'Tablet',
                'stok' => 121,
                'harga_beli' => 302,
                'harga_jual' => 350,
                'kadaluwarsa' => '2026-11-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501157',
                'barcode' => 'O2501157250001',
                'nama_obat' => 'PAPAVERIN 40 MG (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 82,
                'harga_beli' => 487,
                'harga_jual' => 500,
                'kadaluwarsa' => '2026-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500005',
                'barcode' => 'O2500005250001',
                'nama_obat' => 'PARACETAMOL 500MG (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 1028,
                'harga_beli' => 132,
                'harga_jual' => 150,
                'kadaluwarsa' => '2028-01-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500089',
                'barcode' => 'O2500089250001',
                'nama_obat' => 'JKN.PARACETAMOL SUPPO 125mg',
                'satuan' => 'Suppositoria',
                'stok' => 15,
                'harga_beli' => 42033,
                'harga_jual' => 43000,
                'kadaluwarsa' => '2026-11-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501394',
                'barcode' => 'O2501394250001',
                'nama_obat' => 'BLUD.PEDITOX (PHERMETHRIN CAIR)',
                'satuan' => 'Botol',
                'stok' => 14,
                'harga_beli' => 12000,
                'harga_jual' => 12000,
                'kadaluwarsa' => '2027-04-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501738',
                'barcode' => 'O2501738250001',
                'nama_obat' => 'BLUD.SUPERHOID (ANTIHEMOROID)',
                'satuan' => 'Suppositoria',
                'stok' => 6,
                'harga_beli' => 7600,
                'harga_jual' => 7600,
                'kadaluwarsa' => '2027-10-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501124',
                'barcode' => 'O2501124250001',
                'nama_obat' => 'BLUD. PIROXICAM 10MG',
                'satuan' => 'Tablet',
                'stok' => 57,
                'harga_beli' => 250,
                'harga_jual' => 250,
                'kadaluwarsa' => '2028-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500138',
                'barcode' => 'O2500138250001',
                'nama_obat' => 'JKN. RANITIDIN TABLET 150 mg',
                'satuan' => 'Tablet',
                'stok' => 500,
                'harga_beli' => 220,
                'harga_jual' => 250,
                'kadaluwarsa' => '2028-11-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2502878',
                'barcode' => 'O2502878250001',
                'nama_obat' => 'BLUD. Tialisin Syrup',
                'satuan' => 'Botol',
                'stok' => 4,
                'harga_beli' => 7100,
                'harga_jual' => 7100,
                'kadaluwarsa' => '2028-08-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500726',
                'barcode' => 'O2500726250001',
                'nama_obat' => 'BEDAK SALICYL MENTHOL (BLUD)',
                'satuan' => 'Botol',
                'stok' => 26,
                'harga_beli' => 8000,
                'harga_jual' => 8000,
                'kadaluwarsa' => '2028-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501342',
                'barcode' => 'O2501342250001',
                'nama_obat' => 'SIMVASTATIN 10 MG (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 161,
                'harga_beli' => 217,
                'harga_jual' => 250,
                'kadaluwarsa' => '2027-02-28',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501906',
                'barcode' => 'O2501906250001',
                'nama_obat' => 'SPIRONOLACTON 25 MG (JKN)',
                'satuan' => 'Tablet',
                'stok' => 111,
                'harga_beli' => 465,
                'harga_jual' => 500,
                'kadaluwarsa' => '2026-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500499',
                'barcode' => 'O2500499250001',
                'nama_obat' => 'BLUD. VITAMIN B1',
                'satuan' => 'Tablet',
                'stok' => 294,
                'harga_beli' => 123,
                'harga_jual' => 150,
                'kadaluwarsa' => '2028-10-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500183',
                'barcode' => 'O2500183250001',
                'nama_obat' => 'BLUD.VITAMIN B6 10 mg',
                'satuan' => 'Tablet',
                'stok' => 449,
                'harga_beli' => 118,
                'harga_jual' => 150,
                'kadaluwarsa' => '2028-03-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501740',
                'barcode' => 'O2501740250001',
                'nama_obat' => 'BLUD.SCOPMA',
                'satuan' => 'Tablet',
                'stok' => 93,
                'harga_beli' => 1147,
                'harga_jual' => 1500,
                'kadaluwarsa' => '2029-02-28',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501347',
                'barcode' => 'O2501347250001',
                'nama_obat' => 'VITAMIN B12 (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 887,
                'harga_beli' => 98,
                'harga_jual' => 100,
                'kadaluwarsa' => '2029-05-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2502067',
                'barcode' => 'O2502067250001',
                'nama_obat' => 'Vitamin B Kompleks (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 221,
                'harga_beli' => 122,
                'harga_jual' => 150,
                'kadaluwarsa' => '2029-07-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501348',
                'barcode' => 'O2501348250001',
                'nama_obat' => 'VITAMIN C 50MG (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 1514,
                'harga_beli' => 106,
                'harga_jual' => 150,
                'kadaluwarsa' => '2028-02-29',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500066',
                'barcode' => 'O2500066250001',
                'nama_obat' => 'JKN. FITOMENDADION (VIT K)',
                'satuan' => 'Tablet',
                'stok' => 70,
                'harga_beli' => 5500,
                'harga_jual' => 5500,
                'kadaluwarsa' => '2026-08-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500208',
                'barcode' => 'O2500208250001',
                'nama_obat' => 'JKN.  SALBUTAMOL / VENTOLIN NEBULES',
                'satuan' => 'Ampul',
                'stok' => 17,
                'harga_beli' => 6220,
                'harga_jual' => 6500,
                'kadaluwarsa' => '2027-04-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2502004',
                'barcode' => 'O2502004250001',
                'nama_obat' => 'BLUD. NaCL',
                'satuan' => 'Flabot',
                'stok' => 5,
                'harga_beli' => 9400,
                'harga_jual' => 9500,
                'kadaluwarsa' => '2026-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500205',
                'barcode' => 'O2500205250001',
                'nama_obat' => 'JKN. LIDOCAIN INJEKSI',
                'satuan' => 'Ampul',
                'stok' => 84,
                'harga_beli' => 1730,
                'harga_jual' => 2000,
                'kadaluwarsa' => '2026-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501933',
                'barcode' => 'O2501933250001',
                'nama_obat' => 'Glukosa 5 % (D5%) (BLUD)',
                'satuan' => 'Botol',
                'stok' => 5,
                'harga_beli' => 11300,
                'harga_jual' => 11500,
                'kadaluwarsa' => '2027-05-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500918',
                'barcode' => 'O2500918250001',
                'nama_obat' => 'IPF. Isoniazid 300mg/Rifapetine 300mg (TPT 3HP)',
                'satuan' => 'Kaplet',
                'stok' => 160,
                'harga_beli' => 4337,
                'harga_jual' => 4500,
                'kadaluwarsa' => '2027-04-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501239',
                'barcode' => 'O2501239250001',
                'nama_obat' => 'BLUD. Demacolin tab',
                'satuan' => 'Tablet',
                'stok' => 46,
                'harga_beli' => 620,
                'harga_jual' => 650,
                'kadaluwarsa' => '2028-07-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500478',
                'barcode' => 'O2500478250001',
                'nama_obat' => 'Metronidazole 500mg - BLUD',
                'satuan' => 'Tablet',
                'stok' => 82,
                'harga_beli' => 257,
                'harga_jual' => 300,
                'kadaluwarsa' => '2026-06-30',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501188',
                'barcode' => 'O2501188250001',
                'nama_obat' => 'CIPROFLOXACIN 500mg (BLUD)',
                'satuan' => 'Tablet',
                'stok' => 88,
                'harga_beli' => 257,
                'harga_jual' => 300,
                'kadaluwarsa' => '2029-03-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2501468',
                'barcode' => 'O2501468250001',
                'nama_obat' => 'GOM - BLUD',
                'satuan' => 'fls',
                'stok' => 20,
                'harga_beli' => 4250,
                'harga_jual' => 4500,
                'kadaluwarsa' => '2025-12-31',
                'keterangan' => null,
            ],
            [
                'kode_obat' => 'O2500091',
                'barcode' => 'O2500091250002',
                'nama_obat' => 'JKN.PARACETAMOL SIRUP 120 mg/5 ml',
                'satuan' => 'Botol',
                'stok' => 15,
                'harga_beli' => 8000,
                'harga_jual' => 8500,
                'kadaluwarsa' => '2027-08-31',
                'keterangan' => null,
            ],
        ];

        foreach ($obatData as $data) {
            // Cek apakah obat sudah ada
            $existingObat = DB::table('obat')
                ->where('kode_obat', $data['kode_obat'])
                ->orWhere('barcode', $data['barcode'])
                ->first();

            if (!$existingObat) {
                DB::table('obat')->insert(array_merge($data, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ]));
            }
        }
    }
}